### ISSUE TITLE
isic: command not found

### ISSUE THREAD

**Issue by nina-weng** [ImageMarkup/isic-cli#41]
Does anybody meet this problem? 
I successfully installed this package and I could also see it in the pip list. But somehow when I try to download the dataset using the command begin with isic, it failed and told me that command not found.
Anybody could help?

**Comment by danlamanna** [comment]
If you can specify the full location to it it should work.

Assuming you’re on Windows, if you run `pip show isic-cli` it should show the location it was installed in e.g. `c:\users\foo\python\site-packages`. Replacing site-packages with scripts should work, so in this example the final path would be `c:\users\foo\python\scripts\isic`.

So instead of running `isic user login` you would run `c:\users\foo\python\scripts\isic user login`.

We have something planned in the future that should hopefully make this much easier, but for now this is the workaround.

**Comment by nina-weng** [comment]
I am using the server which in linux. I tried the above one but it didn't work for me

**Comment by nina-weng** [comment]
it is actually interesting, because I checked the python/site-packages, the package is there

**Comment by danlamanna** [comment]
And `isic` isn't present in the `bin` directory for python? You may want to resort to using `find / -name "isic" 2> /dev/null` to search for the executable directly.

**Comment by danlamanna** [comment]
Actually, you might be able to run `pip show --files isic-cli | grep bin` to get the path.

**Comment by nina-weng** [comment]
i dont know why I could not do it this way `c:\users\foo\python\scripts\isic user login` (replace the path to the path in my end) TAT

**Comment by nina-weng** [comment]
hiii sorry to the late reply. yes the problem is solved now. Thanks

**Comment by nina-weng** [comment]
(by the way, do you by any chance know where can I find the description of each column in the matadata?

**Comment by danlamanna** [comment]
An unofficial/incomplete list of items is documented [here](https://github.com/ImageMarkup/isic-archive/wiki/Image) but there's nothing published with descriptions of each field, though that is on our roadmap for the future. Were there specific fields you were curious about?
