### ISSUE TITLE
Is there a public disease mapping instructions? 

### ISSUE THREAD

**Issue by nina-weng** [ImageMarkup/isic-cli#43]
Thanks for the developing of this repository! 
I noticed that the download meta data consists around 20-ish diagnosis, I was wondering whether there is a mapping instructions which could categorize those into the 9 categories in ISIC challenge?
i.e.,
1. Melanoma
2. Melanocytic nevus
3. Basal cell carcinoma
4. Actinic keratosis
5. Benign keratosis (solar lentigo / seborrheic keratosis / lichen planus-like keratosis)
6. Dermatofibroma
7. Vascular lesion
8. Squamous cell carcinoma
9. None of the others 

Any information will be appreciated!

**Comment by nina-weng** [comment]
I tried to map by myself, however what the internet told me is that other than the disease mentioned in the 9 categories above, the others are just not included
Not sure if that's the real case in Dermatology

**Comment by nina-weng** [comment]
Thank you so much for this information!
When I said "not sure whether that's the real case in dermatology", I was referring to the fact that when I searched, e.g. which type of the following categories that 'AIMP' belongs to, it told me it does not belong to any of the above 8 categories. I was just wondering whether that's correct from the dermatology's perspective. 
Now I understand the situation here. thanks a lot

**Comment by NickRaymondKurtansky** [comment]
Atypical intraepidermal melanocytic proliferation (AIMP) is a descriptive histopathologic term commonly used in cases to denote morphology sharing some features with melanoma but failing to meet criteria of a definitive benign or malignant diagnosis (Ensslin et al. Atypical Melanocytic Proliferations: A Review of the Literature. Dermatol Surg. 2018).

Some people consider it an _intermediate_ diagnosis while some people are reluctant to use language implying progression since the malignant potential of these lesions is ambiguous.
